openapi: 3.0.0
info:
  title: Textbook Content API
  description: API for accessing textbook content for RAG system
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Local development server

paths:
  /content/modules:
    get:
      summary: Get all textbook modules
      description: Retrieve a list of all available textbook modules with metadata
      responses:
        '200':
          description: List of textbook modules
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Module'

  /content/modules/{moduleId}:
    get:
      summary: Get specific module content
      description: Retrieve content of a specific textbook module
      parameters:
        - name: moduleId
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the module
      responses:
        '200':
          description: Module content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Module'
        '404':
          description: Module not found

  /content/search:
    get:
      summary: Search textbook content
      description: Search across all textbook modules for relevant content
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
          description: Search query string
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
          description: Maximum number of results to return
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/SearchResult'
                  total:
                    type: integer

components:
  schemas:
    Module:
      type: object
      required:
        - id
        - title
        - content
        - sidebar_position
        - file_path
      properties:
        id:
          type: string
          description: Unique identifier for the module
        title:
          type: string
          description: Display title of the module
        content:
          type: string
          description: MDX content of the module
        sidebar_position:
          type: integer
          description: Position in the navigation sidebar
        file_path:
          type: string
          description: Path to the MDX file
        learning_objectives:
          type: array
          items:
            type: string
          description: Learning objectives for the module
        prerequisites:
          type: array
          items:
            type: string
          description: Prerequisite modules

    SearchResult:
      type: object
      properties:
        module_id:
          type: string
          description: ID of the module containing the result
        title:
          type: string
          description: Title of the module
        content_snippet:
          type: string
          description: Snippet of relevant content
        relevance_score:
          type: number
          format: float
          description: Relevance score of the result