openapi: 3.0.3
info:
  title: RAG Chatbot API
  description: API for the Robotics Handbook RAG Chatbot Integration
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.rag-chatbot.example.com
    description: Production server
paths:
  /chat/start:
    post:
      summary: Start a new chat session
      description: Creates a new chat session and returns a session token
      responses:
        '200':
          description: Session created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  session_token:
                    type: string
                    description: Unique token for the chat session
                    example: "a1b2c3d4-e5f6-7890-1234-567890abcdef"
        '500':
          description: Internal server error
      tags:
        - chat
  /chat/{session_token}/message:
    post:
      summary: Send a message to the chatbot
      description: Sends a user message and returns the chatbot's response
      parameters:
        - name: session_token
          in: path
          required: true
          description: Session token for the chat session
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
              properties:
                message:
                  type: string
                  description: The user's message to the chatbot
                  example: "What is ROS 2?"
      responses:
        '200':
          description: Response generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    description: The chatbot's response
                    example: "ROS 2 (Robot Operating System 2) is a set of software libraries and tools that help you build robot applications..."
                  sources:
                    type: array
                    items:
                      type: object
                      properties:
                        document:
                          type: string
                          description: Source document path
                        title:
                          type: string
                          description: Document title
                        content:
                          type: string
                          description: Relevant content snippet
                        score:
                          type: number
                          description: Relevance score
                    description: List of source documents used in the response
                  timestamp:
                    type: string
                    format: date-time
                    description: When the response was generated
        '400':
          description: Invalid request (e.g., empty message)
        '404':
          description: Session not found
        '500':
          description: Internal server error
      tags:
        - chat
  /chat/{session_token}/history:
    get:
      summary: Get conversation history
      description: Retrieves the conversation history for a specific session
      parameters:
        - name: session_token
          in: path
          required: true
          description: Session token for the chat session
          schema:
            type: string
      responses:
        '200':
          description: Conversation history retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: Unique message identifier
                        role:
                          type: string
                          enum: [user, assistant]
                          description: Role of the message sender
                        content:
                          type: string
                          description: Message content
                        timestamp:
                          type: string
                          format: date-time
                          description: When the message was created
                        sources:
                          type: array
                          items:
                            type: object
                            properties:
                              document:
                                type: string
                              title:
                                type: string
                              content:
                                type: string
                              score:
                                type: number
                          description: Sources used in the response (for assistant messages)
                    description: List of messages in chronological order
                  created_at:
                    type: string
                    format: date-time
                    description: When the session was created
        '404':
          description: Session not found
        '500':
          description: Internal server error
      tags:
        - chat
  /ingest/docs:
    post:
      summary: Process and ingest documentation
      description: Processes MDX files from the docs directory and stores embeddings in vector database
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                force:
                  type: boolean
                  description: Force reprocessing of all documents
                  default: false
      responses:
        '200':
          description: Documentation processed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  processed_files:
                    type: array
                    items:
                      type: string
                    description: List of processed file paths
                  status:
                    type: string
                    description: Processing status
                    example: "completed"
                  message:
                    type: string
                    description: Additional processing information
        '500':
          description: Internal server error
      tags:
        - ingestion
      security:
        - admin_auth: []
  /health:
    get:
      summary: Health check
      description: Check the health status of the API
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  timestamp:
                    type: string
                    format: date-time
        '500':
          description: API is unhealthy
      tags:
        - health
components:
  securitySchemes:
    admin_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Admin authentication for ingestion endpoints
tags:
  - name: chat
    description: Chat-related endpoints
  - name: ingestion
    description: Documentation ingestion endpoints
  - name: health
    description: Health check endpoints